[game]
soft_max_players = 150
autosaveenabled = true
autosaveinterval = 30
panic_bunker.show_reason = true
panic_bunker.custom_reason = "HEY [[buddy]. T00 M4NY !!CONNECTIONS! AT THIS $TIME.DATE$ COME BACK [in a minute]]"

[hub]
tags = "lang:en,region:am_n_w,rp:none"

[server]
rules_file = "kromer"

[ooc]
enable_during_round = false

[looc]
enabled_dead = true
enabled_crit = true

[ic]
flavor_text = true
punctuation = true

[lore]
year_offset = 1998

[tips]
enabled = false

[atmos]
max_explosion_range = 4

[admin]
new_player_threshold = 600
alert.min_players_sharing_connection = 3
