# Base configuration preset for SS14 Persistence. On the official server this is loaded before persist.toml
# Related docs https://docs.spacestation14.com/en/general-development/tips/config-file-reference.html

[game]
hostname = "[GIT][GUD] SERVER3"
desc = ". . ."
defaultpreset = "persist"
soft_max_players = 999
autosaveinterval = 30

[hub]
tags = "rp:none"

[infolinks]
bug_report = "https://discord.gg/W5hmHFFs2R"
discord    = "https://discord.gg/puEGkSvejN"
github     = "https://github.com/factoryworker37/server3"

[server]
id = "Server3"
